### ISSUE TITLE
Fit issue

### ISSUE THREAD

**Issue by Bachuganesh2812** [PramitDutta1999/Conv-ViT-A-Convolution-and-Vision-Transformer-Based-Hybrid-Feature-Extraction-Method#1]
Got this error when i am trying to fit the model

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[27], line 2
      1 #Model 
----> 2 history = model.fit(
      3             train_generator,
      4             validation_data = validation_generator,
      5             epochs = 20,
      6             verbose = 1,
      7             callbacks=[ ], #add here
      8             )

File /opt/conda/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_fileo15m2msk.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

File /tmp/__autograph_generated_fileg1npkw3m.py:14, in outer_factory.<locals>.inner_factory.<locals>.tf__call(self, images)
     12 patches = ag__.converted_call(ag__.ld(tf).image.extract_patches, (), dict(images=ag__.ld(images), sizes=[1, ag__.ld(self).patch_size, ag__.ld(self).patch_size, 1], strides=[1, ag__.ld(self).patch_size, ag__.ld(self).patch_size, 1], rates=[1, 1, 1, 1], padding='VALID'), fscope)
     13 patch_dims = ag__.ld(patches).shape[-1]
---> 14 patches = ag__.converted_call(ag__.ld(tf).reshape, (ag__.ld(patches), [ag__.ld(batch_size), -1, ag__.ld(patch_dims)]), None, fscope)
     15 try:
     16     do_return = True

ValueError: in user code:

    File "/opt/conda/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "/opt/conda/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/conda/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "/opt/conda/lib/python3.10/site-packages/keras/engine/training.py", line 1050, in train_step
        y_pred = self(x, training=True)
    File "/opt/conda/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_fileg1npkw3m.py", line 14, in tf__call
        patches = ag__.converted_call(ag__.ld(tf).reshape, (ag__.ld(patches), [ag__.ld(batch_size), -1, ag__.ld(patch_dims)]), None, fscope)

    ValueError: Exception encountered when calling layer 'patches_1' (type Patches).
    
    in user code:
    
        File "/tmp/ipykernel_32/3701414816.py", line 16, in call  *
            patches = tf.reshape(patches, [batch_size, -1, patch_dims])
    
        ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.
    
    
    Call arguments received by layer 'patches_1' (type Patches):
      • images=tf.Tensor(shape=(None, None, None, None), dtype=float32)

**Comment by PramitDutta1999** [comment]
Probably your input image shape was not correct. Please check the input
layer of the notebook.

**Comment by Bachuganesh2812** [comment]
Thanks for responding to my problem. I don’t think the problem will be with the input shape, as per your code the ImageDataGenerator function has the target size set, so it will resize the image to that size I think so. As per your suggestions, sir, I have rechecked the code, and the issue remains the same. I believe that the error is the part where no patches are being generated. I will be really grateful if you can help me out in resolving this error. By the way, I like your approach is solving the retina disease classification by stacking both convolution and  Vision Transformers.

**Comment by PramitDutta1999** [comment]
Dear Ganesh,
First of all, sorry for the late reply. I rechecked my code and the problem
occurred because of the package update. There is no other valid reason that
a patch will not be generated. It's good to know that you liked the work.
The work is published recently. If you want to know more, see the
publication here "https://www.mdpi.com/2313-433X/9/7/140". I am having some
issues with my google drive storage, so I am currently having some problems
with working with this code. If I am able to sort out the code I will
update the repository. Please let me know if you have sorted it out already.
With regards
Pramit Dutta
Portfolio: https://pramitdutta1999.github.io/portfolio/

**Comment by PramitDutta1999** [comment]
I rechecked my code and the problem occurred because of the package update. There is no other valid reason that a patch will not be generated.  I am having some issues with my google drive storage, so I am currently having some problems with working with this code. If I am able to sort out the code I will update the repository. Please let me know if you have sorted it out already.

**Comment by Bachuganesh2812** [comment]
Respected sir,
Thanks for your response. The paper is every informative and helped in my
research work in fundus image classification. If possible can you share me
the libraries version you have used early, i will try to recreate the same
environment so that the code can be run without any problem. I will
definitely look up for resolving the error while using the current version.

With regards,
Bachu Ganesh

**Comment by PramitDutta1999** [comment]
The TensorFlow 2.9.2 version was used. Hope it might help! Looking forward to your work on fundus image classification

**Comment by Bachuganesh2812** [comment]
Respected sir,
                 Thank you for the information sir. I will try with the
following package version and will update you sir.

Thanks & Regards
Bachu Ganesh
